### ISSUE TITLE
Use isTimeWindowComplete API function

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/dealii-adapter#19]
Compatibility issue. See https://github.com/precice/precice/pull/619

**Comment by BenjaminRueth** [comment]
Also make sure to update documentation. See [precice/dealii-adapter wiki page "Build your own adapter"](https://github.com/precice/dealii-adapter/wiki/Build-your-own-adapter)

**Comment by DavidSCN** [comment]
@BenjaminRueth What is the status here?

**Comment by BenjaminRueth** [comment]
I only opened this issue as a reminder and did not start working on it. As far as I know, the issue is currently unassigned.

**Comment by BenjaminRueth** [comment]
dcc3c08 closes this issue. Thanks for the hint @DavidSCN!
