### ISSUE TITLE
Time integration scheme

### ISSUE THREAD

**Issue by DavidSCN** [precice/dealii-adapter#2]
One point to discuss is the choice of a suitable time integration scheme:
There are two frequently used schemes: The one-step-theta method and the Newmark's method.
The one-step-theta method has one parameter to adjust between Euler methods and a Crank-Nicolson scheme. [Newmark's method](https://en.wikipedia.org/wiki/Newmark-beta_method) has two parameters (beta, gamma) and thus more possible combinations to obtain certain properties. Therefore, Newmark's scheme takes slightly more effort in terms of computation and programming.

**Comment by BenjaminRueth** [comment]
One comment on time integration with solvers coupled via preCICE in general: If you do not take special care, usually the order of your time stepping drops to first order. 

The reson for this is that the boundary conditions at the coupling interface are kept constant inside one timestep. The time stepping scheme of the solver (for example Newmark's method) only sees a constant right hand side at the coupling interface. Inside the domain the time stepping is, of course, still of second order. However, in the experiments that I have performed so far the first order error at the boundary was always the dominant one and you did not benefit from a high order time stepping scheme at all.

We try to solve this problem in https://github.com/precice/precice/issues/133.

A quick solution to obtain 2nd order for the Newmark scheme: You probably have to communicate additional data or use old data in your adapter to create an interpolation over time. You can take a look at [this talk](https://mediatum.ub.tum.de/1462603). Here, I modified the adapter for the [elastictube1d](https://github.com/precice/elastictube1d) a bit, such that in the end second order in time is recovered.

**Comment by DavidSCN** [comment]
This is a good hint, thank you very much. Looking at the formulas for the one-step-theta-method I already came up to this question. As mentioned on the slides, you split the load vector according to the scheme: 

d^n+1=d^n+(delta_t/2)*(S(t^n)+S(t^n+1))

This is also, what I found for time dependent loads.

Would you split up the load vector accordingly for the Newmark's method? I'm asking, because I didn't find a reuse of the load vector F(t^n) for the update of the displacement d^n+1 anywhere in the formulas, although a time dependent load vector has been considered. Information from the past is only applied in terms of displacements, velocities and accelerations.

**Comment by uekerman** [comment]
I would vote for the theta-method for the moment. Simply because it is easier to implement. We can still add Newmark's method at a later point in time. 
In the adapter, you could then follow @BenjaminRueth's suggestion (Thanks!).

**Comment by BenjaminRueth** [comment]
**edit:** I added a link to the wikipedia page of Newmark's method, just to make sure that we are on the same page w.r.t notation.

**Comment by BenjaminRueth** [comment]
I would also suggest to first go for the theta method, since it is simpler and we have more experience with it. As soon as this is working, we can take a look at Newmark's method.

**Comment by MakisH** [comment]
Was this closed with some commit? You can always write the issue number to the commit message (e.g. "relevant to #2" or "closes #2" and it will appear here for future reference. ;-)
