### ISSUE TITLE
Use markActionFulfilled

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/dealii-adapter#20]
See https://github.com/precice/precice/pull/631

**Comment by DavidSCN** [comment]
@BenjaminRueth What is the status here?

**Comment by BenjaminRueth** [comment]
I only opened this issue as a reminder and did not start working on it. As far as I know, the issue is currently unassigned.

**Comment by DavidSCN** [comment]
Has dcc3c08 not applied all required changes? Or am I missing something?

**Comment by BenjaminRueth** [comment]
You are perfectly right. We can close this issue :)
