### ISSUE TITLE
Writing velocity information

### ISSUE THREAD

**Issue by j8asic** [precice/dealii-adapter#23]
Can the adapter share structure velocities, like it shares displacements?

**Comment by DavidSCN** [comment]
Not by default, but the velocity is stored in the code anyway, so with you could make it work with a minimal effort.

**Comment by DavidSCN** [comment]
In addition: This is not an actual issue in this adapter. If you have specific adapter or preCICE related questions, feel free to ask them [in our discourse forum](https://precice.discourse.group/) or [gitter chatroom](https://gitter.im/precice/Lobby).
