### ISSUE TITLE
Automate dimension choice

### ISSUE THREAD

**Issue by MakisH** [precice/dealii-adapter#29]
We currently have two variants of the adapter: 2D (default) and 3D (more of an extra that we can easily support). The user currently needs to choose the one or the other at runtime, leading sometimes to confusion or to additional steps for switching between variants (mostly for us).

As discussed in #27, it would be nice to automate this (but not high priority).

**Comment by DavidSCN** [comment]
@MakisH Do you still think this is a valid issue once the restructuring is completed? Otherwise I would have a solution, but it would double the already long compile time.

**Comment by MakisH** [comment]
Let's close this then. One should not really run 3D cases with the deal.II adapter unless they know what they are doing, so this should not be an issue anymore.
