### ISSUE TITLE
Dimension mismatch in 2D for FV based solver

### ISSUE THREAD

**Issue by DavidSCN** [precice/dealii-adapter#5]
In 2D simulations, FV solver have actually a 3D grid (one cell) and just the calculations are treated as quasi 2D, which means the out-of-plane component is neglected. But data (zeros) for the irrelevant component is still existing in the solvers and hence, the adapters are designed to handle 3D data sets. Also, precice gets  3D as parameter in the configuration file.
In FE solvers, the 2D simulation has a real 2D grid and therefore, no 3D data (coordinates and coupling data) is available. 
There are until now two options, to get rid of this problem:
1. A 3D grid is also created in the FE solver and the out-of-plane motion is constrained (zero displacement). Disadvantage: The whole system becomes twice as big in case of linear elements. If higher order elements are selected, it becomes even bigger.
2. We ask with `precice.getDimensions()` for the precice dimension and design the adapter in such a way, that unavailable data is filled with zeros. Then, deal.ii calculates in 2D without telling precice.

Solution 1 can maybe used for first testing. For later, option 2 should be the way to go I guess

**Comment by uekerman** [comment]
I agree: Let's go for option 1 first. We, anyway, want to make the current dealii-"adapter" only an example on how to couple dealii, not a general software layer. 

Some remarks:
* Of course, there are also 2D FV solvers with real 2D data, but let's focus on OpenFOAM for the moment. So FV above should always be understood as OpenFOAM. 
* For quasi-2D, you could also get two layers of preCICE vertices from OpenFOAM, e.g. at z=-0.5 and z=0.5. Then, you have to be careful with the data mapping in preCICE. @MakisH Could you please comment here how this is done for the current OpenFOAM-CCX FSI3.

**Comment by uekerman** [comment]
I guess the 3D FEM in dealii would also be hexahedral elements. This is quite the natural choice. Why would say this is unusual, am I overseeing anything? 
What are the OpenFOAM coordinates for the `Fluid-Mesh-Nodes` in z direction? I guess `Fluid-Mesh-Faces` has z=0, right?

**Comment by DavidSCN** [comment]
A general question: What happens exactly in precice when choosing the z-dead restriction? Are the corresponding z-values filled with zeros? This refers especially to the requested precice data format [x1, y1, z1, ...]

@MakisH  Why is the  `z-dead="true"` restriction in the calculix setup only used in the case of forces. The z-direction mapping for the displacements should also be irrelevant.

**Comment by MakisH** [comment]
I am not very familiar with the internals of the mapping, but the `z-dead="true"` mainly has an effect in the `RadialBasisFctMapping<RADIAL_BASIS_FUNCTION_T>::reduceVector`:

https://github.com/precice/precice/blob/8df2bc4e914cf98937cc8e5c6ddd9073c56dff7b/src/mapping/RadialBasisFctMapping.hpp#L306-L326

This reduces e.g. a 3D vector to 2D and is used in the [`RadialBasisFctMapping<RADIAL_BASIS_FUNCTION_T>:: computeMapping()`](https://github.com/precice/precice/blob/8df2bc4e914cf98937cc8e5c6ddd9073c56dff7b/src/mapping/RadialBasisFctMapping.hpp#L128)

I think that the requested data format would not be affected. In any case, this is only needed in the RBF mapping (for which one should maybe take a [deeper look into the literature](https://github.com/precice/precice/wiki/Literature-guide))

From the [wiki](https://github.com/precice/precice/wiki/Mapping-Configuration#radial-basis-function-mapping):

> The interpolation problem might not be well-defined if you map along an axis-symmetric surface or if you work with quasi-3D solvers. This means, preCICE tries to compute, for example, a 3D interpolant out of 2D information. If so, preCICE throws an error `RBF linear system has not converged` or `Interpolation matrix C is not invertible`. In this case, you can restrict the interpolation problem by ignoring certain coordinates, e.g. `x-dead="true"` to ignore the x coordinate. 

About your next question ([here the respective config file](https://github.com/precice/tutorials/blob/master/FSI/cylinderFlap/OpenFOAM-CalculiX/precice-config_serial.xml)):

> Why is the `z-dead="true"` restriction in the calculix setup only used in the case of forces. The z-direction mapping for the displacements should also be irrelevant.

This is a very good question. If I remember correctly, this has something to do with the fact that we have forces from **one fluid face center** mapped to **two solid nodes** (different number of dimensions) and on the other one we have displacements from **two solid nodes** mapped to **two fluid nodes** (same number of dimensions). @uekerman am I correct? Does the direction (write/read) play any role?

**Comment by DavidSCN** [comment]
This issue has been solved with d20622453f66c58fae6576600fd6a485e29f8b33 (currently) in the develop branch.
