### ISSUE TITLE
Compile error: missing semicolon

### ISSUE THREAD

**Issue by mosayebshams** [precice/dealii-adapter#69]
I encountered a simple compile error while building the adapter due to a missing semicolon in the following lines of the source code:

- File: `elasticity.cc`
  - Line: 99
  - Error: Expected `;`

- File: `nonlinear_elasticity.cc`
  - Line: 274
  - Error: Expected `;`

**Solution:** Adding a semicolon at the end of the mentioned lines resolved the issue for me.

**Environment Information:**
- Ubuntu version: 20.04.1
- C++ version: 9.4.0

**Comment by davidscn** [comment]
The decisive part of your setup is the used deal.II version, I guess. Since recently, a semicolon at the end of the `Assert` macro is mandatory, see https://github.com/dealii/dealii/pull/16026

Thanks for pointing this out, I will fix it on develop.
