### ISSUE TITLE
Switch off precice

### ISSUE THREAD

**Issue by DavidSCN** [precice/dealii-adapter#7]
The adapter is currently only for coupled simulations designed. It is planned to add a "switch on /off" for the precice coupling depending on an input parameter. This would be very useful e.g. in order to test the performance of the solid solver or the simulation setup. 
How could such a feature be implemented? I guess a simple straight forward way would be to wrap the necessary code in an if-statement. I opened up the issue to collect ideas before starting: Is there another preferable and/or commonly used strategy from a programmers perspective?

**Comment by uekerman** [comment]
Yes, this is a useful option. Normally, the adapter should handle this, which in the dealii case is currently directly integrated within the solid solver. So, if-statements are OK for me, but put them in your adapter functions (e.g. `initialize_precice()`), nor directly into the `run()`. That means, you would also need to rewrite `isOngoing` and `finalize` into adapter functions.

**Comment by DavidSCN** [comment]
> That means, you would also need to rewrite `isOngoing` and `finalize` into adapter functions.

Consequently, I would need to shift the whole time loop in a separate function, since the `while()` argument is precice related. However, the overview of 'how the adapter is integrated in the solver', which can be seen easily in the `run()` function, will be reduced.
