### ISSUE TITLE
Better name for dealiiadapter.cc

### ISSUE THREAD

**Issue by uekerman** [precice/dealii-adapter#8]
https://github.com/precice/dealii-adapter/blob/master/dealiiadapter.cc
The name is misleading. It's actually not the adapter, but the adapted solver. 
What is the dealii standard way here? `CoupledElasticProblem.cc` or simply `ElasticProblem.cc` ?
In the first case, should we then also change the class name?

**Comment by uekerman** [comment]
sounds good

**Comment by DavidSCN** [comment]
As we discussed also in #10, this adapter should only provide a minimal example. @uekerman: Should we therefore keep the name, or choose something like `DealiiPreciceSolver.cc` or `IntegratedAdapter.cc`?

**Comment by uekerman** [comment]
We should still change the name. In my opinion, it should reflect the physics. What is standard in dealii?

**Comment by DavidSCN** [comment]
Usually, the physics are reflected. The name should also be consistent with the main solver class. The tutorial, which was the basis for this solver, is named `ElasticProblem`.
I would then appreciate your suggestion `CoupledElasticProblem` for both, the file and the main class.

**Comment by DavidSCN** [comment]
All tutorial cases are named consequently after a step, e.g. the first tutorial is named `step-1`. Naming of programs apart from the tutorials are given in the [dealii code gallery](https://github.com/dealii/code-gallery), but it is inconsistent. I would recommend to use an underscore, hence `coupled_elastic_problem.cc`.
